Repository strapi/client, pull requests merged in 2024-12, with the labels that each got.

#14 chore: rename sdk constructor
  README.md
  src/index.ts
  src/sdk.ts
  tests/unit/index.test.ts
Labels: pr: chore, source: sdk

#15 release: v1.0.0-beta.0
  package.json
Labels: pr: chore, source: sdk

#16 chore(repository): enhance bug report template
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
Labels: pr: chore, source: repository

#17 fix(repository): update bug report template formatting
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
Labels: pr: fix, source: repository

#19 feat: add debug capabilities
  .eslintignore
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
  .husky/pre-commit
  .lintstagedrc
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
  rollup.config.mjs
  scripts/pre-pack.sh
  src/auth/factory/factory.ts
  src/auth/manager.ts
  src/auth/providers/api-token.ts
  src/auth/providers/users-permissions.ts
  src/content-types/collection/manager.ts
  src/content-types/single/manager.ts
  src/http/client.ts
  src/sdk.ts
  src/utilities/index.ts
  src/utilities/request-helper.ts
  src/utilities/url-helper.ts
  src/validators/sdk.ts
  src/validators/url.ts
  tests/unit/auth/providers/api-token.test.ts
  tests/unit/http/client.test.ts
  tests/unit/sdk.test.ts
  tests/unit/utilities/request-helper.test.ts
  tests/unit/utilities/url-helper.test.ts
  tsconfig.json
Labels: pr: feature, source: sdk
