Repository strapi/client, pull requests merged in 2025-02, with the labels that each got.

#42 fix(url-helper): fix url query params transformation
  demo/.strapi-app/pnpm-lock.yaml
  package.json
  pnpm-lock.yaml
  src/utilities/url-helper.ts
  tests/unit/utilities/url-helper.test.ts
Labels: pr: fix, source: utils

#43 release: 1.0.0-beta.2
  package.json
Labels: pr: chore, source: sdk

#44 enhancement(sdk): extend the public type api
  src/index.ts
Labels: pr: enhancement, source: sdk

#46 chore: fix the demo env loading
  .prettierignore
  demo/demo-node-javascript/index.js
  demo/demo-node-javascript/package.json
  demo/demo-node-javascript/pnpm-lock.yaml
  demo/demo-node-javascript/src/index.js
  demo/demo-node-typescript/package.json
  demo/demo-node-typescript/pnpm-lock.yaml
  demo/demo-node-typescript/src/index.ts
Labels: pr: chore, source: demo

#47 fix: send content-type as application/json when necessary
  src/content-types/collection/manager.ts
  src/content-types/single/manager.ts
  tests/unit/content-types/collection/collection-manager.test.ts
  tests/unit/content-types/collection/single-manager.test.ts
Labels: pr: fix, source: sdk

#48 chore: update prettier
  .prettierignore
Labels: pr: chore, source: repository

#49 release: 1.0.0-beta.3
  package.json
Labels: source: repository, pr: release

#50 chore(demo): remove demo prefixes
  README.md
  demo/.strapi-app/scripts/seed.js
  demo/node-javascript/package.json
  demo/node-javascript/pnpm-lock.yaml
  demo/node-javascript/src/index.js
  demo/node-typescript/package.json
  demo/node-typescript/pnpm-lock.yaml
  demo/node-typescript/src/index.ts
  demo/node-typescript/tsconfig.json
  package.json
Labels: pr: chore, source: demo

#52 release: 1.0.0
  package.json
Labels: source: sdk, pr: release

#55 chore: rename sdk-js to client
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
  README.md
  demo/node-javascript/package.json
  demo/node-javascript/pnpm-lock.yaml
  demo/node-javascript/src/index.js
  demo/node-typescript/package.json
  demo/node-typescript/pnpm-lock.yaml
  demo/node-typescript/src/index.ts
  package.json
  rollup.config.mjs
  src/auth/manager.ts
  src/auth/providers/users-permissions.ts
  src/client.ts
  src/errors/strapi.ts
  src/http/client.ts
  src/index.ts
  src/validators/client.ts
  src/validators/index.ts
  tests/unit/client.test.ts
  tests/unit/errors/client-errors.test.ts
  tests/unit/index.test.ts
  tests/unit/validators/strapi-config.test.ts
Labels: pr: chore, source: repository

#56 chore: fix debug string and do not autoopen demo admin
  README.md
  demo/.strapi-app/config/admin.ts
Labels: pr: chore, source: client-demo

#57 fix(http): adjust fetch params to conform to the specification
  .prettierignore
  demo/.strapi-app/scripts/seed.js
  demo/next-server-components/.gitignore
  demo/next-server-components/README.md
  demo/next-server-components/eslint.config.mjs
  demo/next-server-components/next.config.ts
  demo/next-server-components/package.json
  demo/next-server-components/pnpm-lock.yaml
  demo/next-server-components/postcss.config.mjs
  demo/next-server-components/public/.gitkeep
  demo/next-server-components/src/app/favicon.ico
  demo/next-server-components/src/app/globals.css
  demo/next-server-components/src/app/layout.tsx
  demo/next-server-components/src/app/page.tsx
  demo/next-server-components/tailwind.config.ts
  demo/next-server-components/tsconfig.json
  demo/node-javascript/package.json
  demo/node-typescript/package.json
  eslint.config.mjs
  src/http/client.ts
  tests/unit/client.test.ts
  tests/unit/http/client.test.ts
Labels: pr: fix, source: client-http

#58 chore(demo): add better demo scripts
  README.md
  demo/.strapi-app/scripts/seed.js
  demo/next-server-components/src/app/layout.tsx
  package.json
  scripts/demo.sh
Labels: pr: chore, source: client-demo

#59 release: v1.0.1
  package.json
Labels: pr: release

#60 docs: add contribution documentation
  .prettierignore
  CONTRIBUTING.md
  README.md
  package.json
Labels: pr: doc, source: repo
